### ISSUE TITLE
Remove 30 minute timeout from PL task

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/pattern-lab-edition-factorial#4]
After 30 minutes of inactivity in the patternlab files, the patternlab watch process stops
`pattern lab processes automatically time out if their is no command line output in 30 minutes...`

I suggest to remove that setting from the PL watch task.

**Comment by mlnmln** [comment]
@krisimmig This need to be fixed here

https://github.com/factorial-io/pattern-lab-edition-factorial/blob/master/package.json#L18

You added a different runner for pattern lab. 

Can you confirm that the 30 minute limit also exists when using the the `--dev` flag? 

This was the original command I suggested. 

`composer start --dev`

**Comment by krisimmig** [comment]
@mlnmln yes, it still happens with the `--dev` flag.
I think the problem is that it is hardcoded in patternlab itself:
https://github.com/pattern-lab/edition-php-twig-standard/issues/24

Maybe we can create a fork, add the config option and create a merge request to the main patternlab project.

**Comment by mlnmln** [comment]
@krisimmig If that's the case then _every_ developer at Factorial working with PL would have that problem. Could you ask around in company chat if we have an existing workaound? I'd rather not maintain a fork of PL.

**Comment by mlnmln** [comment]
Further work would need to happen here now. 
https://github.com/factorial-io/factorial-frontend-stack/issues/37
