### ISSUE TITLE
Feat: patternlab_path() function needs to be updated when scaffolding for Drupal

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/pattern-lab-edition-factorial#9]
IS:
The **source/_twig-components/functions/path.function.php** does not have the correct patternlab_path() function definition.

SHOULD BE:
The function should be adapted to the currently scaffolded theme with the correct name of the folder:
```php
$function = new Twig_SimpleFunction('patternlab_path', function () {
  $path = getenv('PATTERNLAB_LOCAL_SERVER');
  $THEME_FOLDER = "theme_folder_name";
  return $path == "1" ? "" : "/sites/all/themes/custom/" . $THEME_FOLDER . "/source";
});
```

- when scaffolding a new drupal project, can this function be updated with the correct THEME_FOLDER name automatically?
- should we throw an error/warning when not using the phab scaffolder (instead using the composer create command)? The error/warning can tell the user that the THEME_FOLDER placeholder should be updated when integrating with drupal.

**Comment by mlnmln** [comment]
paging @stmh for additional input.

**Comment by stmh** [comment]
patternlab_path is not part of the edition, so i think we can close that here. @krisimmig @mlnmln  anny objections?

**Comment by krisimmig** [comment]
@stmh that´s true, where is that function defined again for the drupal scafolder?

Maybe for now we can just change the default **path.function.php** and change `path` to `patternlab_path`. That way no matter which way you scaffold a project, we will always be able to use the **patternlab_path()** function in the templates.

https://github.com/factorial-io/pattern-lab-edition-factorial/blob/master/source/_twig-components/functions/path.function.php#L3

**Comment by stmh** [comment]
the default path function does sth completely different and we should not override it with patternlab_path. I'd vote to use the scaffolder to create the function, as it is an implementation detail of the drupal patternlab integration.

**Comment by mlnmln** [comment]
> the default path function does sth completely different and we should not override it with patternlab_path. I'd vote to use the scaffolder to create the function, as it is an implementation detail of the drupal patternlab integration.

Yes, agreed this does not belong here. 

However we still need to solved this to habe a complete solution going from 

-> phab scaffold -> pl-edition -> pl-starterkit 

without devs needing to make manual changes after the project was scaffolded.

**Comment by krisimmig** [comment]
@stmh I think using the phab scaffolder is the only way? Since we don't know the theme folder name before anyway..

**Comment by stmh** [comment]
I added the function template to the bi-d7 scaffolder, so should work out of the box.

**Comment by mlnmln** [comment]
@krisimmig could you verify that this is working?

**Comment by krisimmig** [comment]
@mlnmln @stmh This is working now. The patternlab_path function is correctly scaffolded.
